# Generated by Django 3.2.7 on 2021-09-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beach',
        ),
    ]
