# Generated by Django 3.2.7 on 2021-09-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0002_delete_beach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
